import { ReduxProvider } from './store/provider';
import { Space_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'



const sm = Space_Mono({ subsets: ['latin'] , weight:'400' })

export const metadata = {
  title: 'ALCOSTORE',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">

       <body className={sm.className}>
       <header>
        <Link href='/'>
          <div className='logo'/>
          </Link>
        </header>
          <ReduxProvider>
              {children}
           </ReduxProvider>
       <footer> 
          <span style={{display: 'block'}}>© This is footer copyright</span>
        </footer>
       </body>

    </html>
  )
}
