import { ReduxProvider } from './store/provider';
import { Space_Mono } from 'next/font/google'
import './globals.css'
import Header from './components/Header';
import Footer from './components/Footer'
const sm = Space_Mono({ subsets: ['latin'] , weight:'400' })

export const metadata = {
  title: 'ALCOSTORE',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">

       <body className={sm.className}>

          <ReduxProvider>
          <Header/>
              {children}
           </ReduxProvider>
      <Footer/>
       </body>
    </html>
  )
}
